- installer/centos/build.sh
No longer compiling PyQT5 and PyQTGraph. Environment variables updated for all users.
> CentOS install: global paths and faster install

- installer/centos/uninstall.sh
uninstalls HNN itself, but dependencies are left installed
> uninstall script for CentOS

- installer/centos/centos6-installer.sh
By installing a full-featured version of NEURON we don't risk breaking an existing NEURON setup.
> installs full-featured version of NEURON

- installer/windows/hnn.ps1
I realized that the powershell install script wasn't properly instructing users to change their working directory to the hnn repo before starting the GUI. These changes will output the correct instructions for users.
> Clarify commands to start hnn on Windows

- installer/docker/Dockerfile
- installer/docker/docker-compose.yml
- installer/windows/windows-install.md
Please see the following two commits for an Ubuntu docker image that should work for all platforms. Install instructions for Windows have been completed and are part of this pull request.
HNN is run as a non-privileged user within the container. Related to issue #25
> Docker install

- installer/centos/README.md
- installer/docker/README.md
- installer/mac/README.md
- installer/ubuntu/README.md
- installer/windows/README.md
- installer/windows/docker-compose.yml
This commit includes instructions for using the Docker container on
each platform (CentOS/Ubuntu/Mac/Windows). The instructions have been
updated to recommend an IP address that will not go away as external
network connectivity changes. This means that the HNN GUI will remain
running even after a laptop screen is closed or Wi-Fi locations have
changed.
The procedure for Windows is slightly simplified by using a consistent
IP address for the DISPLAY environment variable. Docker Desktop will
create this interface and it will likely be the same for all users.
> Use markdown for all instructions including Docker

- installer/README.md
- installer/centos/README.md
- installer/centos/native_install.md
- installer/mac/README.md
- installer/mac/native_install.md
- installer/mac/troubleshooting.md
- installer/ubuntu/README.md
- installer/ubuntu/native_install.md
- installer/windows/README.md
- installer/windows/native_install.md
In order to make it more apparent that the docker-based installation is
the recommended method, separate the native install instructions into a
separate file that a user would have to intentionally chose (marked for
advanced users).
Include instructions on creating a Docker Hub account in Mac and
Windows guides.
Also separate troubleshooting page for Mac into its own file.
> Split install instructions into different files

- installer/docker/README.md
With Linux, an xhost command may be necessary to allow docker to display
to the X server. This commit also updated and cleaned up existing
troublshooting text
> Add the xhost fix to docker troubleshooting

- installer/docker/Dockerfile
- installer/docker/start_hnn.sh
This was causing some users trouble when XQuartz would unexpectedly use
a different display port. Just try them all because it is pretty fast,
but give users meaningful messages in the debug output.
> Update docker container to try all known DISPLAY's

- hnn_qt5.py
Use psutil library and thread locks to ensure spawned nrniv processing
get killed. Handler where mpiexec fails on systems with hyperthreading
enabled by retrying with use-hwthreads --use-hwthread-cpus option.
Also print nrniv banner only when not in opt mode
> Fix handling of nrniv child processes

- installer/centos/README.md
- installer/docker/Dockerfile
- installer/docker/docker-compose.yml
- installer/docker/start_hnn.sh
- installer/mac/docker-compose.yml
- installer/mac/docker-desktop.md
- installer/mac/docker-toolbox.md
- installer/ubuntu/README.md
- installer/windows/docker-compose.yml
- installer/windows/docker-desktop.md
- installer/windows/docker-toolbox.md
This ensures that the directory is created by hnn_user instead of
root. The instructions have been updated to use docker-compose up
instead of docker-compose run to ensure that the container name
remains consistent.
Fixes #82
> Update docker build to create hnn_out as user

- simdat.py
This makes the plots of the theoretical input timing distibution
look better by summing the input distributions before plotting.
Thanks to @rythorpe for the solution
> ENH: plot sum of evoked input histograms

- installer/docker/Dockerfile
- installer/docker/date_base_install.sh
- installer/docker/hooks/build
Label with current date and VCS reference. This will allow docker
hub builds to use the build cache for layers corresponding to
installing packages.
Also write the date that base packages were last updated to
/base-install
> MAINT: docker hub build hook for labeling

- simdat.py
- spikefn.py
By default, the 'bins' parameter is now optimized within spikefn.py (hopefully without breaking any other calls to the spikefn.plot_hist() function).
Here are some samples of the new histogram output:
> Optimize bin width of input time histograms for each type of input.

- hnn_qt5.py
- simdat.py
If experimental data is shorter than simulation data, the functions
that calculate regular and weighted RMSE will downsample the
simulation data to match the number of samples in experimental data.
However, the start and stop ranges were not aligned. This patch
finds the shortest common range before performing downsampling.
> Fix RMSE calc when exp data is shorter

- hnn_qt5.py
If the stop simulation button was pressed before a simulation actually
started, then HNN would crash with this exception. Note that a user
was unlikely to get this error unless the filesystem was particularly
slow (e.g. Oscar).
> BUG: handle psutil.NoSuchProcess exception

- hnn_qt5.py
During optimization, we update the ranges before running the 4th
and final step with all inputs. If the updating finds that two
inputs are too close to optimize separately, they will be combined
and the total number of optimization steps will decrease. This was
improperly checked before.
> BUG: recalculate last step in case it has changed

- hnn_qt5.py
This was a mistake in using the join() method on a list. Now the
system also has adequeate time to check for killed process. The
fact that this error happened at all means there was a problem
stopping the processes. This is the best we can do within Python.
Fixes issue #109
> BUG: fix improper use of str.join()

- hnn_docker.sh
- installer/docker/troubleshooting.md
- installer/mac/docker-desktop.md
- installer/windows/docker-compose.yml
- installer/windows/docker-desktop.md
- installer/windows/docker-toolbox.md
This commit finishes support for hnn_docker.sh in Windows. It
changes the install procedure to require Git for Windows and
commands are run from 'Git Bash' instead of cmd.exe.
Fixes #125
> ENH: support hnn_docker.sh in windows

- hnn_docker.sh
If xquartz was not set up to use authentication. The script would
fail because it didn't enable authentication before trying to run
the xauth command. This commit turns authentication on before
trying to restart xquartz.
> BUG: fix enabling xquartz authenication

- hnn_qt5.py
- installer/docker/Dockerfile
Also pegs NEURON in container to branch 7.7
Setting OMPI_MCA_btl_vader_single_copy_mechanism=none was necessary
for NEURON simulations to finish correctly. If a lot of simulations
(e.g. 25) are run, then NEURON would hang, results wouldn't display
in HNN, and 'Stop Simulations' would have to be pressed.
https://github.com/open-mpi/ompi/issues/4948
> BUG: fix issue not completing 25 trials

- hnn_qt5.py
Optimization would crash on the deepcopy of simdat.ddat because it
contains open file handles that couldn't be serialized. We only
need to save the dipole data ('dpl') and the calculated RMSE
('errtot').
Fixes issue #136
> BUG: only copy needed data to inital_ddat

- hnn_docker.sh
If HNN has been running for 10s before it exited, then don't
automatically try restarting the container. The purpose of
the restart was for failures of the GUI to show up at all. If
it's been 10s, then the GUI probably popped up.
> ENH: don't always retry starting HNN

- gutils.py
Also orient main GUI window at the top of the display, centered
left to right.
> ENH: set maximum window height for dual monitors

- clidefs.py
- dipolefn.py
- hnn_qt5.py
- pspec.py
- simdat.py
- spikefn.py
- visrast.py
Do not raise a fatal exception when trying to read data files. Just
handle the exception and plot as much as possible with the loaded
data (if any).
New readtxt function in simdat.py and revamped updatedat that
uses readtxt
Fixes #115
> ENH: handle exceptions when loading files

- specfn.py
Because of a numpy change, the parameter allow_pickle needs to be
explicitly set to True.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html
Fixes #129
> BUG: fix saving figures

- hnn_docker.sh
On macOS, try using the system xauth (returned by
` which xauth`), but if it fails, default to the
hardcoded path for the XQuartz version of xauth.
This is a fix for systems that have /usr/bin/xauth
leftover from the Apple-provided X11 server with
Snow Leopord.
Fixes #188
> ENH: mac: use XQuartz xauth

- conf.py
- installer/aws/README.md
- installer/centos/README.md
- installer/docker/Dockerfile
- installer/docker/README.md
- installer/docker/docker-compose.yml
- installer/docker/hnn_envs
- installer/docker/start_hnn.sh
- installer/mac/docker-compose.yml
- installer/mac/docker-desktop.md
- installer/mac/docker-toolbox.md
- installer/mac/native_install.md
- installer/ubuntu/README.md
- installer/windows/docker-compose.yml
- installer/windows/docker-desktop.md
- installer/windows/docker-toolbox.md
This updates the default output directory when HNN is run inside a docker container to be hnn_out on the **system OS**, not `/home/hnn_user/hnn_out` inside the container. This is accomplished by sharing the user's home directory with the docker container using the same name as on the system OS.
Thanks @klankinen for the idea. 
Documentation is updated, but this should result in a more intuitive placement of output files.
The docker container is also updated to result in a smaller total image without any large layers (faster parallel pull).
> Update default hnn_out path in docker

- scripts/docker_functions.sh
Since Docker Desktop 2.3.0.4, paths on the host system can be addressed
without using "C:\" syntax which required MSYS_NO_PATHCONV=1
Fixes issue #217
> [MRG] BUG: windows: docker changed conventions for paths

- installer/mac/native_install.md
- installer/windows/docker-desktop.md
- installer/windows/docker-toolbox.md
- scripts/docker_functions.sh
The old link to 1.20.1.4 directed users to install a version of VcXsrv that didn't work with `hnn_docker.sh`! This corrects the instructions and adds a troubleshooting section on the bug. Also reverts a previous commit to use `127.0.0.1:0` instead of `localhost:0` for the display name in an attempt to fix this problem.
> [MRG] DOC: give correct VcXsrv version for windows + docker

- .travis.yml
- scripts/setup-travis-mac.sh
- spikefn.py
- tests/test_compare_hnn.py
- tests/test_view_windows.py
- visdipole.py
- vispsd.py
- visrast.py
- visspec.py
Just like we initialize the main HNN GUI window (hnn_qt5.py) during testing and then have it gracefully exit with `TRAVIS_TESTING=1`, we can do the same with windows showing dipole, raster, spectrogram, and PSD plots. This PR adds tests for each of those windows that simply initializes the window and then exits. If there no uncaught exceptions, then the process that started the window will exit successfully and the test will pass.
Tests can be improved further in #232 (a test for somatic voltages should be added). Having this in place will allow for catching errors potentially exposed by #236. 
Resolves #243
> [WIP] TST: add view window tests

- .travis.yml
- installer/ubuntu/hnn-ubuntu.sh
The installation script seems to work fine for Ubuntu 20.04 (Focal Fossa) (only tested for a single machine, though, which was not a fresh installation). The only necessary change is a new arm in the switch statement that sets the corresponding python version.
> Added ubuntu 20.04 to installation script

- hnn_qt5.py
Previously, data files that were comma-separated (instead of whitespace) would cause an exception on loading.
Also, change the exception dialog to not reference "hnn_docker.log"
> ENH: read data files that are comma-delimited

- hnn/paramrw.py
- hnn/qt_dipole.py
- hnn/qt_evoked.py
- hnn/qt_lib.py
- hnn/qt_main.py
- hnn/qt_psd.py
- hnn/qt_sim.py
- hnn/qt_thread.py
- hnn/simdata.py
- scripts/run-pytest.sh
- setup.cfg
This PR is about fixing the remaining bugs in the optimization code and "reproducing" the optimization tutorial.
> MRG: optimization updates after hnn-core integration

- hnn/qt_spike.py
When tstop is not divisible by 5.0 (global, yuck!), the histogram
that gets created is too small for the x-axis of the plots. Use
ceil() to round up.
Fixes #177
> MRG: get number of hist bins using ceil, not int

- hnn/qt_sim.py
Check that sim_data['spec'] has valid for each trial. Previously
only checked the length was > 0, but when there is a failure
loading spec data, there is a list of None. Need to check that
data for each trial isn't None.
Fixes #290
> MRG: BUG: check that spec data loaded before plotting

- hnn/qt_main.py
Fixes two issues:
1. If an exception was triggered to early, a second exception about
waitsimwin because it hadn't been created in HNNGUI.__init__() yet.
2. If an exception occurs loading a parameter file or other GUI activity
when a simulation isn't running, a "Simulation failed" message still
pops up.
> [MRG] MAINT: fixup excepthook handler

- hnn/qt_evoked.py
The list of tabs that cleanLabels used to find and remove references
to GUI objects was deleted before it could iterate through. So objects
didn't get dereferenced.
Fixes #295
> [MRG] BUG: clean GUI objects before removing opt tab
