installer/centos/centos6-installer.sh

This is slightly better than the 7 installer (which should be renamed now that this exists to avoid ambiguity) because it cleans up after itself. This definitely works when the whole thing is run as root. sudo will probably time out otherwise (but that's configurable).

CentOS 6 installer

---

installer/README.md
installer/centos/README.md
installer/docker/README.md
installer/mac/README.md
installer/ubuntu/README.md
installer/windows/README.md

We recommend the docker-based install for all users. The native install
using scripts or step-by-step procedures are best suited for advanced
users.

Clarify which installs are for advanced users

---

installer/docker/README.md
installer/mac/README.md
installer/windows/README.md

Had to remove the drop-down style menus for instructions to display
properly on github.io

Compatibility with github.io pages

---

installer/centos/README.md
installer/centos/native_install.md
installer/mac/docker-desktop.md
installer/mac/docker-toolbox.md
installer/mac/native_install.md
installer/ubuntu/README.md
installer/windows/docker-desktop.md
installer/windows/docker-toolbox.md
installer/windows/native_install.md

- Add caveat about Model Visualization not working on Mac
with Docker Desktop
- Correct spelling of 'clicking'
- Correct spelling of 'bullentin'

Fix typos and small corrections

---

installer/README.md
installer/virtualbox/README.md

These are the instructions exported from the web page, then reformatted
in markdown.

Adding VirtualBox instructions

---

simdat.py

Evoked input arrows plotted in main dipole window scale to both the x- and y-axis

Evoked input arrow scaling

---

hnn_qt5.py

Fix unit labeling of CaT and HCN channel density

---

hnn_qt5.py
installer/docker/Dockerfile
param/ERPYesSupraT.param
paramrw.py
simdat.py

Enables optimization feature in HNN. Once data and param files have been loaded, a "Configure Optimization" option is enabled.
ERPYesSupraT was used to test and evaluate the optimization scheme. Since std. dev. is a parameter that will be estimated, N_trials for ERPYesSupraT.param is changed to 3.
** There is a bug in this code where the display mode changes for optimization results and remains while the program is running **

ERP Optimization

---

simdat.py

This made plot creation inconsistent with previous plots

Revert change in subplot left offset.

---

hnn.cfg
hnn_qt5.py
params_default.py

Makes optimization results reproducible

Set random number generator seed for nlopt

---

hnn_qt5.py

Fixes issue where if a user specifies a max of 0.1, the GUI will reset to 1.9

BUG: opt: allow user to specify range via min/max

---

simdat.py

14.6 after rounding to 2 digits, should read 14.60

Fix RMSE display to include trailing 0's

---

simdat.py

BUG: don't assume sims have been run in plotextdat

---

simdat.py

BUG: fix breaking change 6bc6aea

---

hnn
hnn.desktop
hnn.sh
installer/aws/aws-build.sh
installer/brown_ccv/oscar_setup.sh
installer/brown_ccv/vnc-client.md
installer/brown_ccv/x11-forwarding.md
installer/centos/centos6-installer.sh
installer/centos/centos7-installer.sh
installer/centos/native_install.md
installer/centos/uninstall.sh
installer/docker/Dockerfile
installer/docker/README.md
installer/docker/start_hnn.sh
installer/mac/docker-desktop.md
installer/mac/docker-toolbox.md
installer/mac/native_install.md
installer/mac/troubleshooting.md
installer/ubuntu/installer.sh
installer/ubuntu/native_install.md
installer/ubuntu/uninstaller.sh
installer/ubuntu/updater.sh
installer/windows/docker-desktop.md
installer/windows/docker-toolbox.md
installer/windows/hnn.ps1
installer/windows/native_install.md

1. hnn.cfg is no longer needed, just "python3 hnn.py"
2. major changes to Dockerfile: software rendering of network viz works, include nlopt and psutil
3. singularity run hnn.simg works
4. warning messages on Oscar are resolved

HNN GUI startup changes

---

hnn_qt5.py

For increased performance (17s to 16s). Also avoids warning messages.

Disable hyperthreading

---

simdat.py
spikefn.py

Also set the ymax to be the same for all histograms
Before:
After:

Turn off x-axis tickmarks for histograms

---

hnn_qt5.py

New optimization dialog with updated formatting:

Include param delta in optimization dialog

---

hnn_qt5.py

Cleans up scheme for creating basedir and saving param file

BUG: create new dir for data and params at start

---

hnn_qt5.py

properly remove parameters from optimization

properly remove parameters from optimization

---

hnn_qt5.py

Fixes #106 after previous fix caused different failure

BUG: put back dqline in OptEvokedInputParamDialog

---

spikefn.py

BUG: return valid spike_list even if empty

---

installer/mac/README.md
installer/mac/docker-desktop.md
installer/mac/docker-toolbox.md
installer/mac/native_install.md
installer/mac/troubleshooting.md
installer/virtualbox/README.md

Include troubleshooting steps for macOS 10.15 (Catalina). Fix some typos and misc. clarifications.

DOC: update mac install docs and troubleshooting

---

hnn_docker.sh
installer/centos/README.md
installer/docker/Dockerfile
installer/docker/docker-compose.yml
installer/docker/start_hnn.sh
installer/mac/docker-desktop.md
installer/mac/docker-toolbox.md
installer/ubuntu/README.md
installer/windows/docker-desktop.md
installer/windows/docker-toolbox.md

hnn_docker script for linux

---

conf.py
hnn_qt5.py
paramrw.py

Significant optimization rewrite aimed at:
1) implement range slider mechanism for the user to interactively change optimization ranges even after optimization had started
2) simplify the model of holding data relevant to optimization: ranges, number of simulations, number of parameters, and optimization results

Range slider

---

hnn_qt5.py
paramrw.py

Improve range slider interface and if the user moves the sliders, then keep the setting until "Reset Ranges" is pressed.

Optimization update

---

hnn_qt5.py

Fix the order in which tabs are removed from the optimization dialog.
Fixes #143

BUG: fix loading param files w/o evoked inputs

---

hnn_docker.sh
installer/windows/docker-desktop.md
installer/windows/docker-toolbox.md

Also handle checking if a docker pull actually updated the image
before removing the existing container with ./hnn_docker.sh -u start

BUG: kill vcxsrv.exe the right way in Windows

---

hnn_docker.sh

This fixes a bug when running hnn_docker.sh in Linux where the script
would stop if an existing running container was found. The fix will
try to restart the container so that it can start the GUI.
Also consolidate error handling messages in cleanup function and
write more output to hnn_docker.log

BUG: complete hnn_docker.sh when container found

---

hnn_qt5.py
paramrw.py
params_default.py
run.py
simdat.py
vislfp.py
visspec.py

Uses value in params_default.py when a parameter file hasn't been loaded

Set the default colormap

---

hnn_qt5.py
installer/docker/Dockerfile

BUG: fix list join again

---

hnn_docker.sh

Also cleans up log messages
Completes fix to #163

BUG: fix creating ssh keys

---

installer/docker/Dockerfile

BUG: wrong repo for HNN source in Dockerfile

---

run.py
specfn.py

Print the traceback to the Simulation Log and to console

ENH: handle exceptions during NERUON sim

---

installer/windows/hnn.ps1
installer/windows/native_install.md

MAINT: fix Windows native install with tblshooting

---

hnn_docker.sh

BUG: tell xauth which .Xauthority

---

hnn_docker.sh

Immediately copy SSH keys after creating container to remove need
to check if keys need to be copied in. Also use verbose option to
capture output from ssh command.
Added in response to issue #163

MAINT: clean up logic docker image

---

.travis.yml
hnn_docker.sh
installer/docker/docker-compose.yml
installer/mac/docker-compose.yml
installer/ubuntu/installer.sh
installer/windows/docker-compose.yml

Test more Ubuntu distros and older OS X versions back to El Capitan.
For windows, just test native GUI, and allow functions in hnn_docker.sh to fail. Test code to start qemu virtual machine and docker is commented out until the build gets sorted ou

Expand Travis testing to more targets

---

.travis.yml
hnn_docker.sh
hnn_qt5.py
installer/docker/Dockerfile
installer/docker/QtProject.conf
installer/docker/README.md
installer/docker/check_hnn_out_perms.sh
installer/docker/check_sshd.sh
installer/docker/check_sshd_port.sh
installer/docker/check_x_port.sh
installer/docker/docker-compose.yml
installer/docker/start_hnn.sh
installer/docker/start_ssh.sh
installer/mac/docker-compose.yml
installer/windows/docker-compose.yml
scripts/utils.sh
tests/test_compare_hnn.py

TST: run docker build for linux tests
TST: enable tests to be run on development code
ENH: QT file dialog window improvements
BUG: reliably start sshd when using hnn_docker.sh

hnn_docker.sh reliability, shortcuts to folders, and docker tests on current code

---

.travis.yml
hnn_docker.sh
installer/docker/check_x_port.sh
installer/docker/start_hnn.sh
scripts/utils.sh

Allows the X server to use any port, not just :0. Also fixes up
output in hnn_docker.sh and travis.yml while using new functions.

ENH: hnn_docker.sh: support any X port

---

hnn_docker.sh

BUG: windows: xauth generate handle paths with " "

---

hnn_docker.sh
installer/docker/check_x_port.sh
scripts/utils.sh

BUG: windows: need to set initial DISPLAY

---

README.md

[MRG] DOC: update README with hnn-core mention

---

scripts/docker_functions.sh

MAINT: docker: windows: use IP address for xauth

---

installer/mac/README.md
installer/mac/check-post.sh
installer/mac/check-pre.sh
installer/mac/troubleshooting.md

This resolves problems found in #256 (thanks @lzimbalist)

Minor fixes to Mac OS Python install instructions

---

installer/ubuntu/hnn-ubuntu.sh

Fixes issue #265. Thanks @hisakof for reporting it.

MAINT: skip verifying certificates on HNN download (ubuntu)

---

hnn_models/hnn_A1/mod/dipole.mod
hnn_models/hnn_A1/mod/dipole_pp.mod

@salvadord dipole modfiles seem to be needed here, otherwise the example fails to run.

missing mod files for A1 example

---

hnn/paramrw.py
hnn/qt_sim.py
hnn/simdata.py

Found an exception on a linux VM when save_figs was true, but save_spec was 0, and no rhythmic feeds were defined.

BUG: savefigs exception

---

hnn/qt_sim.py

MRG: BUG: use linewidth from HNNGUI to plot SimCanvas

---

hnn/qt_main.py

Requires hnn-core:f8a4b05608 (now merged)

MRG: ENH: record_vsoma can run with ncore > 1

---

hnn/paramrw.py

MRG: BUG: don't check for old rhythmic params

---

hnn/qt_psd.py

MAINT: sys import

---

hnn_api/network.py

This is my first COMMIT !
Importing OrderedDict

My first COMMIT Hnn2 

---

installer/centos/README.md

[MRG] update link to centos installation script

---

installer/mac/README.md

DOC: download environment.yml and set fallback dynamic library path during mac installation 
